apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fleetpulse
resources:
  - namespace.yaml
  - configmaps.yaml
  - data.yaml
  - applications.yaml
  - observability.yaml
  - services.yaml
  - policies.yaml
  - disruption-budgets.yaml

